### ISSUE TITLE
Deploy to streamlit hub after open sourcing

### ISSUE THREAD

**Issue by dleve123** [factula/sumtool#74]
- set up some CI pipeline to automatically deploy, perhaps

**Comment by srush** [comment]
Oh I think if we make it public?

**Comment by srush** [comment]
Oh it is public. I think you are an organization owner @anton164 .

**Comment by anton164** [comment]
Hmmm, I dont see the org in the https://share.streamlit.io/ dropdown  (weirdly I see your account there).
<img width="328" alt="Screenshot 2022-03-03 at 15 38 26" src="https://user-images.githubusercontent.com/1349225/156648967-e35252c5-0135-44f1-a3d8-446f53419618.png">

Do you see the factula org in this dropdown?

**Comment by anton164** [comment]
Looks like someone added the org, so it works now:
- GH pages url: https://factula.github.io/sumtool/
- Streamlit URL: https://share.streamlit.io/factula/sumtool/main/interface/app.py

We need to fix the sumtool package installation (publish to pip?) for this work. As far as I know it is not possible to install a repository package from streamlit. Requirements are installed based on requirements.txt

**Comment by srush** [comment]
works now https://share.streamlit.io/factula/sumtool/ !
